### PR TITLE
Update CHACHA20 cipher ids

### LINKED ISSUE #155: Chacha cipher IDs are not from published RFC
The numerical IDs at the https://wiki.mozilla.org/Security/Server_Side_TLS use the numbers from agl draft, not the published RFC (https://tools.ietf.org/html/rfc7905).

The RFC uses the following IDs:

```
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256   = {0xCC, 0xA8}
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 = {0xCC, 0xA9}
```

while the document uses those IDs:

```
0xCC,0x14  -  ECDHE-ECDSA-CHACHA20-POLY1305  TLSv1.2  Kx=ECDH  Au=ECDSA  Enc=ChaCha20(256)  Mac=AEAD
0xCC,0x13  -  ECDHE-RSA-CHACHA20-POLY1305    TLSv1.2  Kx=ECDH  Au=RSA    Enc=ChaCha20(256)  Mac=AEAD
```

### PR DESCRIPTION
**Pull request by liggitt**
Ids taken from https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml

Fixes #155

### CODE REVIEW

**Comment by tomato42** [comment]
I think the old ones should be left in, but marked as old (because they are widely deployed)

**Comment by liggitt** [comment]
I could see a comment, but I don't think the non-standard ones should remain as distinct rows

**Comment by lukastribus** [comment]
Where are exactly are the draft ciphers widely deployed?

Google services don't support them, and other than older boringssl builds I don't think any ssl lib does. OpenSSL certainly never did.

So unless there is evidence about widespread adoption, I suggest we drop 'em. Its complicated enough already, no need to further confuse everyone with obsolete pre-standard ciphers ids.

**Comment by jvehent** [comment]
Cloudflare deploys then, and cloudflare is a wide chunk of the internet, thus the ciphers are widely deployed.

That said, I don't disagree about dropping them entirely.

**Comment by liggitt** [comment]
updated with a note, PTAL

**Comment by liggitt** [comment]
@jvehent any other feedback?

**Review by tomato42 — APPROVED** [review]

**Pull request merged**
