### PR TITLE
Adding Tomcat and JSSE support

### LINKED ISSUE #82: Add support for Tomcat 7 + 8
Tomcat is not a currently listed server, so there is no profile for a HTTPS connector. Would be great to have one added so Coyote can be used to serve HTTPS in a modern, secure manner.

### PR DESCRIPTION
**Pull request by gene1wood**
Extending Steve Springett's PR #153 by converting tomcat cipher strings from static lists to a generated string derived from the openssl cipher lists. This should resolve #82

Added csv data of iana and openssl cipher names and codes

Added method to convert openssl cipher names to iana cipher names

Added missing ciphers to tomcat cipher lists
- https://svn.apache.org/viewvc/tomcat/trunk/java/org/apache/tomcat/util/net/openssl/ciphers/Cipher.java?r1=1720602&r2=1720601&pathrev=1720602

Changing from the openssl cipher list for the "old" profile to a new version which
- doesn't use "+" and "!" macros
- expands "kEDH+AESGCM" "AES" "HIGH" and "SEED" to their constituent ciphers
- changes "DHE-RSA-DES-CBC3-SHA" to "EDH-RSA-DES-CBC3-SHA"
- Removes
  - ECDHE-ECDSA-AES256-CCM8
  - ECDHE-ECDSA-AES256-CCM
  - DHE-RSA-AES256-CCM8
  - DHE-RSA-AES256-CCM
  - ECDHE-ECDSA-AES128-CCM8
  - ECDHE-ECDSA-AES128-CCM
  - DHE-RSA-AES128-CCM8
  - DHE-RSA-AES128-CCM
  - AES256-CCM8
  - AES256-CCM
  - AES128-CCM8
  - AES128-CCM
  - ECDHE-ECDSA-CAMELLIA256-SHA384
  - DHE-RSA-CAMELLIA256-SHA
  - DHE-DSS-CAMELLIA256-SHA
  - CAMELLIA256-SHA256
  - CAMELLIA256-SHA
- Adds
  - DHE-RSA-CAMELLIA256-SHA
  - DHE-DSS-CAMELLIA256-SHA
  - CAMELLIA256-SHA256
  - CAMELLIA256-SHA
- swaps the order of
  - ECDHE-ECDSA-CAMELLIA256-SHA384
  - ECDHE-RSA-CAMELLIA256-SHA384
  - to
  - ECDHE-RSA-CAMELLIA256-SHA384
  - ECDHE-ECDSA-CAMELLIA256-SHA384
- swaps the order of
  - ECDHE-ECDSA-CAMELLIA128-SHA256
  - ECDHE-RSA-CAMELLIA128-SHA256
  - to
  - ECDHE-RSA-CAMELLIA128-SHA256
  - ECDHE-ECDSA-CAMELLIA128-SHA256

Fixed bug from 5e48ccb7e8b98ce31dad0ff04ddd538087441091 where a duplicate line was added of sslProtocols for `old` `lighttpd`

Changed HSTS max-age to match the existing max-age settings

### CODE REVIEW

**Comment by gene1wood** [comment]
@marumari would you review my PR?

**Comment by gene1wood** [comment]
This PR adds in `TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256` and `TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256`. I've confirmed that tomcat 7.0.54 supports these ciphers. I've also confirmed that tomcat will accept a cipher name in it's cipher list which it doesn't know about and gracefully ignore it.

**Comment by stevespringett** [comment]
This PR is so old it now has conflicts, which didn't exist when it was made. Any idea when this can be merged in?

**Comment by gene1wood** [comment]
@jvehent I'd asked @april to take a look at this PR but it didn't come together. Would you take a look and merge if it looks good?

**Comment by april** [comment]
August 30, 2016. Yikes! My bad!

**Comment by april** [comment]
I would like to see this format in something that is easy to work with, like JSON, instead of CSV. Could we make that change?

**Comment by gene1wood** [comment]
@april The reason CSV was used for `ianaTlsCipherSuiteNames` is that that is the format of the [source data presented from IANA](https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-4). We'd have to convert the source data (and if it ever changes or is updated convert it each time) from CSV to JSON. I think it makes most sense to consume this in it's native format.

I'm assuming @stevespringett opted to use CSV for the `opensslCipherSuites` because he was already using CSV for the cipher suite names but this could be done in JSON just as easily.

@april What do you think about leaving `ianaTlsCipherSuiteNames` as CSV and switching `opensslCipherSuites` to JSON?

**Comment by stevespringett** [comment]
@gene1wood that is correct. The end format needs to be CSV in the Tomcat config, so I opted to use CSV for the ciphersuites as well.

**Comment by april** [comment]
I see. I mean, I already have code that can parse the IANA format and convert it to JSON, although it certainly may have bugs at this point. @jvehent, what do you think?

**Comment by gene1wood** [comment]
Here's a block that would generate the `opensslCipherSuites` in JSON format would be

    // json/openssl-ciphersuites.json is produced by running
    // openssl ciphers -V ALL:COMPLEMENTOFALL | python -c 'import fileinput,json; print(json.dumps(dict([(x.split()[2], x.split()[0]) for x in fileinput.input()])))' > openssl-ciphersuites.json
    // Add in deprecated names : https://www.openssl.org/docs/manmaster/man1/ciphers.html#Older-names-used-by-OpenSSL
    // openssl ciphers -V EDH-RSA-DES-CBC3-SHA:EDH-DSS-DES-CBC3-SHA | python -c 'import fileinput,json,sys; y=json.load(open(sys.argv[1])); y.update(dict([(x.split()[2].replace("DHE-","EDH-"), x.split()[0]) for x in fileinput.input("-")])); json.dump(y, open(sys.argv[1], "w"), indent=4)' openssl-ciphersuites.json

**Comment by april** [comment]
If you'd be willing to submit a template here, I'd be happy to accept it:
https://github.com/mozilla/ssl-config-generator

Thanks!

**Pull request closed without merging**
