### PR TITLE
Update versions

### PR DESCRIPTION
**Pull request by Sp1l**
Add all newer released versions for
 - Apache httpd
 - Nginx
 - Haproxy
 - OpenSSL (apart from 1.1.1, pending TLSv1.3)

### CODE REVIEW

**Review by tomato42 — APPROVED** [review]

**Comment by tomato42** [comment]
Please [rebase](https://help.github.com/articles/about-git-rebase/) your PR on top of current master branch, then [force push](https://stackoverflow.com/a/10510482/462370) to the same branch as this PR is using.

Do not merge the `master` branch to this branch to update it.

**Review by tomato42 — CHANGES_REQUESTED** [review]
as in comment above

**Comment by gene1wood** [comment]
@tomato42 Looks good to me. Shall we just squash merge this PR to collapse the 4 commits?

**Review by tomato42 — APPROVED** [review]
ok, provided the commits are squashed

**Pull request merged**
