### PR TITLE
Update Server_Side_TLS.mediawiki

### PR DESCRIPTION
**Pull request by warburtr0n**
New branch (I think) with all the requested changes.

### CODE REVIEW

**Comment by jvehent** [comment]
Looking great! I'll merge it now. Thanks so much for writing this section, I think a lot of people will find it useful :)

**Comment by warburtr0n** [comment]
Awesome, thanks so much. Glad you like it :) Thanks for helping create such a great resource in the first place!

**Comment by warburtr0n** [comment]
Daft question... (I'm still a total n00b with Github!)... when will the change be live on the Moz wiki? I was just going to send around an internal email once it's up...

**Comment by jvehent** [comment]
I _just_ pressed that button :) https://wiki.mozilla.org/Security/Server_Side_TLS#F5_BIG-IP

**Pull request merged**
