### PR TITLE
Better defaults for HAProxy

### PR DESCRIPTION
**Pull request by yajo**
Redirects with 301 HTTP to HTTPS and adds cipher and options by default to all SSL binds and servers.

### CODE REVIEW

**Comment by jvehent** [comment]
That looks good, thanks for the patch. Do you know if those parameters are available on all version of haproxy >= 1.5 ?

**Comment by yajo** [comment]
Yes.

Actually with this settings you get the HSTS header only in the HTTPS site, since redirection is performed before header injection. But it's still better than it was.

**Comment by lgarron** [comment]
> you get the HSTS header only in the HTTPS site

Reminder: that is the correct behaviour.

https://tools.ietf.org/html/rfc6797#section-7.2

**Comment by yajo** [comment]
Oh nice

**Pull request merged**
