### PR TITLE
Make the intro section look a lot neater

### PR DESCRIPTION
**Pull request by april**
Removes the Mozilla logo and shrinks the generator image a bit.

### CODE REVIEW

**Comment by jvehent** [comment]
but but but... teh logo!?!

**Comment by april** [comment]
It is impressively ugly and memorable, I will give it that.  :)

**Comment by jvehent** [comment]
right, so it's perfect for cybersecuritay !

first, they take away your logos....

**Comment by april** [comment]
Next thing you know, I'll be telling you that you have to wear ties into the home office!

**Comment by jvehent** [comment]
I'm really sorry but aesthetic changes must go through the branding team first... :smiling_imp:

**Comment by gene1wood** [comment]
:shipit:

**Comment by jvehent** [comment]
Wait... I didn't merge this? woops...

**Pull request merged**
